#
#    Copyright 2022 Felipe Joglar
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

[versions]
kotlin = "1.6.21"
androidBuildTools = "7.1.3"

core-ktx = "1.7.0"
compose = "1.2.0-beta01"
activity-compose = "1.4.0"
lifecycle = "2.4.1"

sqlDelight = "1.5.3"

junit = "4.13.2"

androidx-junit = "1.1.3"
espresso = "3.4.0"

[libraries]
# classpath
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidBuildTools = { module = "com.android.tools.build:gradle", version.ref = "androidBuildTools" }
sqlDelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }

# dependencies
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

sqlDelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-native-driver = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }

# test
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

# androidTest
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-compose-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

[bundles]
androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material",
]