name: Setup Xcode
description: Setup Xcode version

runs:
  using: "composite"
  steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      shell: bash

    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      shell: bash