name: Setup Gradle & JDK
description: Setup Gradle and JDK

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'