name: Setup Gradle and JDK
description: Setup Gradle and JDK

inputs:
  cache-key:
    description: Key for managing the Gradle cache
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2