name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew androidBuild

      - name: Run Unit tests
        run: ./gradlew androidTest

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew androidUiTest