name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macos-12

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.3.app
        
      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test
        run: sudo xcodebuild clean build test -workspace apps/ios/Taskodoro.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.4" ONLY_ACTIVE_ARCH=YES