name: iOS CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/actions/*
      - .github/workflows/ios_ci.yml
      - apps/ios/*
      - taskodoro/*
      - build.gradle.kts
      - settings.gradle.kts
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
    branches: [ main ]
    paths:
      - .github/actions/*
      - .github/workflows/ios_ci.yml
      - apps/ios/*
      - taskodoro/*
      - build.gradle.kts
      - settings.gradle.kts

env:
  IOS_DEVICE: iPhone 15 Pro
  IOS_VERSION: 17.2

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: ./.github/actions/gradle-setup

      - name: Setup Xcode
        uses: ./.github/actions/xcode-setup

      - name: Build
        run: sudo xcodebuild clean build -workspace apps/ios/Taskodoro.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=${{ env.IOS_DEVICE }},OS=${{ env.IOS_VERSION }}" ONLY_ACTIVE_ARCH=YES

  unit-tests:
    name: Unit Tests
    needs: [build]
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: ./.github/actions/gradle-setup

      - name: Setup Xcode
        uses: ./.github/actions/xcode-setup

      - name: Run Unit Tests
        run: sudo xcodebuild clean test -workspace apps/ios/Taskodoro.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=${{ env.IOS_DEVICE }},OS=${{ env.IOS_VERSION }}" ONLY_ACTIVE_ARCH=YES