name: Multiplatform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macos-12

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew multiplatformBuild

      - name: Run Unit tests
        run: ./gradlew multiplatformTest