name: Multiplatform CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/multiplatform_ci.yml
      - taskodoro
      - build.gradle.kts
      - settings.gradle.kts
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
    branches: [ main ]
    paths:
      - .github/workflows/multiplatform_ci.yml
      - taskodoro
      - build.gradle.kts
      - settings.gradle.kts

jobs:
  build:
    name: Build
    runs-on: macos-13
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: ./.github/actions/gradle-setup

      - name: Build
        run: ./gradlew taskodoro:clean taskodoro:assemble

  unit-tests:
    name: Unit Tests
    needs: build
    runs-on: macos-13
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: ./.github/actions/gradle-setup

      - name: Run Unit tests
        run: ./gradlew taskodoro:clean taskodoro:allTests