name: Multiplatform CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/actions/*
      - .github/workflows/multiplatform_ci.yml
      - taskodoro/*
      - build.gradle.kts
      - settings.gradle.kts
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
    branches: [ main ]
    paths:
      - .github/actions/*
      - .github/workflows/multiplatform_ci.yml
      - taskodoro/*
      - build.gradle.kts
      - settings.gradle.kts

concurrency:
  group: multiplatform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Build & Test
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/gradle-setup

      - name: Run Spotless
        run: ./gradlew spotlessCheck

      - name: Run Detekt
        run: ./gradlew taskodoro:detekt

      - name: Build
        run: |
          ./gradlew taskodoro:clean taskodoro:assemble 
          ./gradlew infra:database:clean infra:database:assemble 
          ./gradlew infra:preferences:clean infra:preferences:assemble

      - name: Run Unit Tests
        run: ./gradlew taskodoro:clean taskodoro:allTests